### ISSUE TITLE
SerialResponseFilter does not work because it is instantiated for each request

### ISSUE THREAD

**Issue by amartinunowhy** [laszlourszuly/atlantis#47]
To simulate updates, we need the same endpoint to send different response for each request. We tried to use `SerialResponseFilter` for that, but it appears that it is recreated for each request. In consequence, its `index` variable is always 0 and it returns always the same response.

**Comment by laszlourszuly** [comment]
I don't even know how to begin this replay, now, more than three years later. The short and and technical answer: version 4.0.0 of Atlantis, which is a bit of a revival version of the project, has this fixed and verified. There is a bit of a feature loss with this version, though. Hope it doesn't hit you too hard (if still at all interested).
